// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from Cellbots.proto

package com.cellbots.cellserv.client;

import com.google.gwt.core.client.*;

public final class AudioVideoFrame extends JavaScriptObject  {

    public static final class Encoding extends JavaScriptObject {
            
        public static final Encoding JPEG = create(1);
        public static final Encoding H263 = create(2);
        public static final Encoding H264 = create(3);
        public static final Encoding MP3 = create(4);
        public static final Encoding AAC = create(5);
        public static final Encoding WAV = create(6);
        
        private static native Encoding create(int number) /*-{
            return [number];
        }-*/;
        
        protected Encoding() {}
        
        public native int getNumber() /*-{
            return this[0];
        }-*/;
        
        // dev mode
        public static native JsArray<Encoding> getArray(JavaScriptObject obj, String key) /*-{
            var v = obj[key];
            if(v && v.length && !v[0].length) {
                for(var i=0,l=v.length; i<l; i++)
                    v[i] = [v[i]];
            }
            return v;
        }-*/;

        public static native Encoding get(JavaScriptObject obj, String key) /*-{
            var v = obj[key];
            if(v == null)
                return [1];
            return v.length ? v : (obj[key] = [v]);
        }-*/;
    }

    /**
     * Creates a new AudioVideoFrame instance 
     *
     * @return new AudioVideoFrame instance
     */
    public static native AudioVideoFrame create() /*-{
        return {
                        
        };
    }-*/;

    /**
     * Creates a new JsArray<AudioVideoFrame> instance 
     *
     * @return new JsArray<AudioVideoFrame> instance
     */
    public static native JsArray<AudioVideoFrame> createArray() /*-{
        return [];
    }-*/;

    /**
     * Gets a AudioVideoFrame (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return AudioVideoFrame
     */
    public static native AudioVideoFrame get(JavaScriptObject jso) /*-{
        return jso;
    }-*/;
    
    /**
     * Gets a JsArray<AudioVideoFrame> (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return JsArray<AudioVideoFrame> 
     */
    public static native JsArray<AudioVideoFrame> getArray(JavaScriptObject jso) /*-{
        return jso;
    }-*/;
    
    /**
     * Parses a AudioVideoFrame from a json string
     *
     * @param json string to be parsed/evaluated
     * @return AudioVideoFrame 
     */
    public static native AudioVideoFrame parse(String json) /*-{
        return eval("(" + json + ")");
    }-*/;
    
    /**
     * Parses a JsArray<AudioVideoFrame> from a json string
     *
     * @param json string to be parsed/evaluated
     * @return JsArray<AudioVideoFrame> 
     */
    public static native JsArray<AudioVideoFrame> parseArray(String json) /*-{
        return eval("(" + json + ")");
    }-*/;
    
    /**
     * Serializes a json object to a json string.
     *
     * @param AudioVideoFrame the object to serialize
     * @return String the serialized json string
     */
    public static native String stringify(AudioVideoFrame obj) /*-{
        var buf = [];
        var _1 = obj["timestamp"];
        if(_1 != null)
            buf.push("\"timestamp\":" + _1);
        var _2 = obj["data"];
        if(_2 != null)
            buf.push("\"data\":\"" + _2 + "\"");
        var _3 = obj["frameNumber"];
        if(_3 != null)
            buf.push("\"frameNumber\":" + _3);
        var _4 = obj["sourceID"];
        if(_4 != null)
            buf.push("\"sourceID\":\"" + _4 + "\"");
        var _5 = obj["whiteBalance"];
        if(_5 != null)
            buf.push("\"whiteBalance\":" + _5);
        var _6 = obj["zoomLevel"];
        if(_6 != null)
            buf.push("\"zoomLevel\":" + _6);
        var _7 = obj["compressionLevel"];
        if(_7 != null)
            buf.push("\"compressionLevel\":" + _7);
        var _8 = obj["widthPx"];
        if(_8 != null)
            buf.push("\"widthPx\":" + _8);
        var _9 = obj["heightPx"];
        if(_9 != null)
            buf.push("\"heightPx\":" + _9);
        var _10 = obj["timeSpan"];
        if(_10 != null)
            buf.push("\"timeSpan\":" + _10);
        var _11 = obj["lightOn"];
        if(_11 != null)
            buf.push("\"lightOn\":" + _11);
        var _12 = obj["encoding"];
        if(_12 != null)
            buf.push("\"encoding\":" + _12);

        return buf.length == 0 ? "{}" : "{" + buf.join(",") + "}";
    }-*/;
    
    public static native boolean isInitialized(AudioVideoFrame obj) /*-{
        return true;
    }-*/;
    
    protected AudioVideoFrame() {}

    // getters and setters

    // timestamp

    public native double getTimestamp() /*-{
        return this["timestamp"] || 0;
    }-*/;

    public native void setTimestamp(double timestamp) /*-{
        this["timestamp"] = timestamp;
    }-*/;

    public native void clearTimestamp() /*-{
        delete this["timestamp"];
    }-*/;

    public native boolean hasTimestamp() /*-{
        return this["timestamp"] != null;
    }-*/;

    // data

    public native String getData() /*-{
        return this["data"];
    }-*/;

    public native void setData(String data) /*-{
        this["data"] = data;
    }-*/;

    public native void clearData() /*-{
        delete this["data"];
    }-*/;

    public native boolean hasData() /*-{
        return this["data"] != null;
    }-*/;

    // frameNumber

    public native double getFrameNumber() /*-{
        return this["frameNumber"] || 0;
    }-*/;

    public native void setFrameNumber(double frameNumber) /*-{
        this["frameNumber"] = frameNumber;
    }-*/;

    public native void clearFrameNumber() /*-{
        delete this["frameNumber"];
    }-*/;

    public native boolean hasFrameNumber() /*-{
        return this["frameNumber"] != null;
    }-*/;

    // sourceID

    public native String getSourceID() /*-{
        return this["sourceID"] || "";
    }-*/;

    public native void setSourceID(String sourceID) /*-{
        this["sourceID"] = sourceID;
    }-*/;

    public native void clearSourceID() /*-{
        delete this["sourceID"];
    }-*/;

    public native boolean hasSourceID() /*-{
        return this["sourceID"] != null;
    }-*/;

    // whiteBalance

    public native int getWhiteBalance() /*-{
        return this["whiteBalance"] || 0;
    }-*/;

    public native void setWhiteBalance(int whiteBalance) /*-{
        this["whiteBalance"] = whiteBalance;
    }-*/;

    public native void clearWhiteBalance() /*-{
        delete this["whiteBalance"];
    }-*/;

    public native boolean hasWhiteBalance() /*-{
        return this["whiteBalance"] != null;
    }-*/;

    // zoomLevel

    public native int getZoomLevel() /*-{
        return this["zoomLevel"] || 0;
    }-*/;

    public native void setZoomLevel(int zoomLevel) /*-{
        this["zoomLevel"] = zoomLevel;
    }-*/;

    public native void clearZoomLevel() /*-{
        delete this["zoomLevel"];
    }-*/;

    public native boolean hasZoomLevel() /*-{
        return this["zoomLevel"] != null;
    }-*/;

    // compressionLevel

    public native int getCompressionLevel() /*-{
        return this["compressionLevel"] || 0;
    }-*/;

    public native void setCompressionLevel(int compressionLevel) /*-{
        this["compressionLevel"] = compressionLevel;
    }-*/;

    public native void clearCompressionLevel() /*-{
        delete this["compressionLevel"];
    }-*/;

    public native boolean hasCompressionLevel() /*-{
        return this["compressionLevel"] != null;
    }-*/;

    // widthPx

    public native int getWidthPx() /*-{
        return this["widthPx"] || 0;
    }-*/;

    public native void setWidthPx(int widthPx) /*-{
        this["widthPx"] = widthPx;
    }-*/;

    public native void clearWidthPx() /*-{
        delete this["widthPx"];
    }-*/;

    public native boolean hasWidthPx() /*-{
        return this["widthPx"] != null;
    }-*/;

    // heightPx

    public native int getHeightPx() /*-{
        return this["heightPx"] || 0;
    }-*/;

    public native void setHeightPx(int heightPx) /*-{
        this["heightPx"] = heightPx;
    }-*/;

    public native void clearHeightPx() /*-{
        delete this["heightPx"];
    }-*/;

    public native boolean hasHeightPx() /*-{
        return this["heightPx"] != null;
    }-*/;

    // timeSpan

    public native int getTimeSpan() /*-{
        return this["timeSpan"] || 0;
    }-*/;

    public native void setTimeSpan(int timeSpan) /*-{
        this["timeSpan"] = timeSpan;
    }-*/;

    public native void clearTimeSpan() /*-{
        delete this["timeSpan"];
    }-*/;

    public native boolean hasTimeSpan() /*-{
        return this["timeSpan"] != null;
    }-*/;

    // lightOn

    public native boolean getLightOn() /*-{
        return this["lightOn"] || false;
    }-*/;

    public native void setLightOn(boolean lightOn) /*-{
        this["lightOn"] = lightOn;
    }-*/;

    public native void clearLightOn() /*-{
        delete this["lightOn"];
    }-*/;

    public native boolean hasLightOn() /*-{
        return this["lightOn"] != null;
    }-*/;

    // encoding

    public native Encoding getEncoding() /*-{
        return @com.cellbots.cellserv.client.AudioVideoFrame.Encoding::get(Lcom/google/gwt/core/client/JavaScriptObject;Ljava/lang/String;)(this, "encoding");
    }-*/;

    public native void setEncoding(Encoding encoding) /*-{
        this["encoding"] = encoding;
    }-*/;

    public native void clearEncoding() /*-{
        delete this["encoding"];
    }-*/;

    public native boolean hasEncoding() /*-{
        return this["encoding"] != null;
    }-*/;

}
